### ISSUE TITLE
app_folder_name should not be recursive

### ISSUE THREAD

**Issue by acerbetti** [Jems22/fastlane-plugin-increment_version_code#5]
Hi, thank you for the plugin. I'm facing an issue. The wrong build.gradle is chosen because it has a similar path. 

> 
> [17:07:42]: The get_version_code plugin is looking inside your project folder (android/app)!
> [17:07:42]: new version code = 38
> [17:07:42]:  -> Found a build.gradle file at path: (node_modules/react-native/local-cli/templates/HelloWorld/android/app/build.gradle)!

Here is my simplelane
```
increment_version_code(
      app_folder_name: "android/app",
      version_code: options[:build_number]
)
```

**Comment by Jems22** [comment]
The version 0.4.1 should fix your issue.
You can now set the gradle_file_path property to specify the gradle file you want to use.
