### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by grifotv** [Jems22/fastlane-plugin-increment_version_code#8]
I had this in my project and it was working fine. However, today it stopped working out of the blue:

```
It seems like you wanted to load some plugins, however they couldn't be loaded
Please follow the troubleshooting guide: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md
```

```
[!] Could not find action, lane or variable 'increment_version_code'. Check out the documentation for more details: https://docs.fastlane.tools/actions
```

**Comment by grifotv** [comment]
Wonder if it's an actual fastlane error

**Comment by Jems22** [comment]
Hi @grifotv.
That weird. I expect this is a fastlane error.
There is no reason for the plugin stop working, and, it's still working  on my side. Do you still have this issue ?

**Comment by grifotv** [comment]
@Jems22 I just upgraded fastlane from `2.60.0` to `2.60.1` and is now working fine.

Closing this issue.
